<a href="https://colab.research.google.com/github/macanoso/Deep-Learning/blob/main/Third%20Week/03_1_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

Most of the data analysis which needs data to be stored in memory uses Numpy

Why not lists? memory memory memory

## Numpy Arrays

All elements of a NumPy array should be of same type. Considering the mathematical operations that can be performed on them. It would not be possible with heterogeneous data sets

It also provides a mechanism of specifying the data types of the contents, which allows further optimisation of the code.

In [8]:
import numpy as np
import sys

mylst = [1,2,3,4,5,6]
numpy_arr = np.array([1,2,3,4,5,6])

sizeof_mylst = sys.getsizeof(1) * len(mylst)           
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size

print('tamaño de la lista:', sizeof_mylst)
print('tamaño del np array:', sizeof_numpy_arr)

tamaño de la lista: 168
tamaño del np array: 48


In [9]:
# For NumPy arrays elements limited to 1 Byte / 8 Bits
numpy_arr2 = np.array([1,2,3,4,5,6], dtype = np.int8)
sizeof_numpy_arr2 = numpy_arr2.itemsize * numpy_arr.size   # Size = 6
print(sizeof_numpy_arr2)

# For NumPy arrays elements limited to 2 Bytes / 16 Bits
numpy_arr3 = np.array([1,2,3,4,5,6], dtype = np.int16)
sizeof_numpy_arr3 = numpy_arr3.itemsize * numpy_arr.size   # Size = 12
print(sizeof_numpy_arr3)



6
12


In [10]:
mylst = ["Hello", "World", "Students", "of", "Deep", "Learning"]
numpy_arr = np.array(["Hello", "World", "of", "Deep", "Learning"])

sizeof_mylst = sys.getsizeof("Hello") * len(mylst)     # Size  > 300
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size   # Size = 80

print(sizeof_mylst)
print(sizeof_numpy_arr)

324
160


In [11]:
mylst = [1.1, 1.2,1.3424242, 1.436654646546, 454353.1232131, 32434353.324324, 1234.2321]
numpy_arr = np.array([1.1, 1.2,1.3424242, 1.436654646546, 454353.1232131, 32434353.324324, 1234.2321])

sizeof_mylst = sys.getsizeof(12345.232343) * len(mylst)           # Size  = 196
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size   # Size = 56

print(sizeof_mylst)
print(sizeof_numpy_arr)

168
56


An n-dimension array is generally used for creating a matrix or tensors.

The dimensions of the array can be changed at runtime as long as the multiplicity factor produces the same number of elements: A 2 * 5 matrix can be converted into 5 * 2 and a 1 * 4 into 2 * 2. This can be done by calling the NumPy .reshape(...) function.

In [12]:
import numpy as np
# A 2 * 5 matrix
np_md_arr = np.array ( [ 
                        [1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10]
                        ] )

# Creates a 5 * 2 Matrix
# [ [1,2], [3,4], [5,6], [7,8], [9,10]]
np_modmd_arr = np_md_arr.reshape(5,2)

# A 1 * 4 Matrix
np_md_arr2 = np.array ( [1, 2, 3, 4] )

# Creates a 2 * 2 Matrix
#[ [1,2], [3,4] ]
np_modmd_arr2 = np_md_arr2.reshape(2,2)

print("2x5:", np_md_arr)
print("5x2:", np_modmd_arr)
print("2x2:", np_modmd_arr2)


2x5: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5x2: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2x2: [[1 2]
 [3 4]]


NumPy can also generate a predefined set of number for an array. A predefined set of numbers with steps (including decimal steps can be generated using numpy.arange(...) function.

In [25]:
import numpy as np

# Generating predefined data using aranage function

np_nd_arr1 = np.arange(0,10)
# Generates => [0 1 2 3 4 5 6 7 8 9]
np_nd_arr2 = np.arange(0,10,2)
# Generates => [0 2 4 6 8] . The 3rd parameter '2' is step

# The step could be in floating point
np_nd_arr3 = np.arange(0,10,0.5)
# Generates => [ 0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]

# Generating n-dimension array from the output
np_nd_arr4 = np_nd_arr1.reshape(5,2)
"""
Generates the following
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
"""
np_nd_arr5 = np_nd_arr3.reshape(4,5)
"""
Generates the following
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]
"""
display(np_nd_arr1,
        np_nd_arr2,
        np_nd_arr3,
        np_nd_arr4,
        np_nd_arr5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

NumPy create n-dimension arrays using pre-filled ones and zeros (matrix values are either zero or one). One of the most probable usage of this is to create a Sparse or Dense matrix for machine learning.

By default, NumPy uses floating point float64 data type for creating ones and zeros, however, the data type can be changed to integer using dtype parameter.

In [26]:
import numpy as np

np_array_zeros = np.zeros(10)
# Generates => [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
np_array_ones = np.ones(10)
# Generates => [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np_array = np.zeros((2,5))
"""
Generates the following
[[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]]
"""
np_array = np.ones((2,5))
"""
Generates the following
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
"""
# Changing the datatype as Integer
np_array = np.ones((2,5), dtype='int32')
"""
Generates the following
[[1 1 1 1 1]
 [1 1 1 1 1]]
"""
print(np_array)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
# Math calculations

np_arr = np.array([1,2,3]) * 2
# Generates [2,4,6]
print(np_arr)

np_arr = np.array([1,2,3]) + 2
# Generates [3,4,5]

np_arr1 = np.array([[1,2,3],[4,5,6]])
np_arr2 = np.array([[1,2,3],[4,5,6]])
np_arr3 = np_arr1 * np_arr2
#Generates
# [[ 1  4  9]
# [16 25 36]]

np_arr3 = np_arr1 + np_arr2
#Generates
# [[ 2  4  6]
# [ 8 10 12]]

np.sqrt(np_arr1)
#generates
# [1.         1.41421356 1.73205081]
# [2.         2.23606798 2.44948974]]
np.mean(np_arr1) #generates 3.5
np.median(np_arr1) #generates 3.5

display(np_arr1.sum(), # 21
np_arr1.min(),  # 1
np_arr1.max())  # 6

[2 4 6]


21

1

6

## Finding Elements in NumPy array

While working with data sets there will be times when we need to find specific data from the available data set. These three will be used more often than others. where, nonzeroand count_nonzero.

Where and nonzero functions returns the index associated with the True statement.

In [17]:
np_arr = np.array([1,2,0,4,5])
find = np.where(np_arr > 2)  # se leería como... ¿cuales posiciones tienen valores mayores a 2?
#returns [3,4]
print(find)

find2 = np.nonzero(np_arr)  # se leería como... ¿cuales posiciones tienen valores diferentes de cero?
print(find2)

n_arr = np.array([1,2,3,0,3,0,2,0,0,2])
np.count_nonzero(n_arr) #count_nonzero cuenta el número de elementos diferentes de cero
# returns 6

(array([3, 4]),)
(array([0, 1, 3, 4]),)


6

In [18]:
# find the shape of the NumPy array.

n_arr1 = np.array([1.,2,3,0,3,0,2,0,0,2])
n_arr1.shape
# Generates => (10,)
print(n_arr1.shape)

n_arr2 = np.array([[1,2],[3,0]])
# Generates => (2,2)
print(n_arr2.shape)


(10,)
(2, 2)


In [19]:
# Slicing NumPy Arrays
''' The ':' is called the separator and works with Inclusive — Exclusive principal,
which means that the left of the separator shall be included while right of the
separator will be excluded.'''

import numpy as np

np_arr = np.array([1,2,3,4,5,6])

np_arr[:]    # All Elements of an array
np_arr[0:2]  # Elements Index ] -> 0 & 1
np_arr[1:4]  # Elements Index] -> 1,2, & 3
np_arr[0:]   # Elements Index] -> Starting from 0 till end
np_arr[1:4]  # Elements Index -> 1,2, & 3
np_arr[:4]   # Elements Index Starting from 0 till 4
np_arr[-2:]


array([5, 6])

In [20]:
# Numpy has the ability to change multiple elements of the array in-place with a value.

import numpy as np

np_arr = np.array([1,2,3,4,5])

np_arr[:] = 100  # All elements shall be change to 100
print(np_arr)


[100 100 100 100 100]


In [21]:
np_arr[1:3] = -50 # Element index 1,2 & 3 changed to 200
print(np_arr)


[100 -50 -50 100 100]


In [22]:
np_arr[2:] = 100  # Element index starting from 2 till end will be changed to 100
print(np_arr)


[100 -50 100 100 100]


In [23]:
# Here are some examples on what slicing means in case of 2D arrays

import numpy as np

np_arr = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9]])

np_arr[:]        # Display all rows and columns                    
np_arr[:,:]      # Display all rows and columns
np_arr[0:3, 0:3] # Display all rows and columns
np_arr[0:2]      # Display 0th row & 1st Row and All Columns (Since Columns are not specified)
np_arr[0:3,0:2]  # Display all rows but only 0th and 1st column i.e (0, 1) exluding 2
np_arr[:,1]      # Display all rows but only 2nd column 
np_arr[:,0:2]    # Display all rows and 0th and 1st Column

print(np_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
